id: P006638
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W15274
  title: ཚད་མ་རྣམ་འགྲེལ་རིགས་མཛོད་ཆེན་མོ
  author: ''
  volumes:
    47ffa980b3c4458d96b957593e0470b4:
      image_group_id: I2483
      title: ''
      volume_number: 1
      total_pages: 406
      base_file: v001.txt
    87e27bfcc2dc4620a3dc83c4201268f7:
      image_group_id: I2484
      title: ''
      volume_number: 2
      total_pages: 408
      base_file: v002.txt
